---
title: "Major cleaning round"
author: "Noelle Schenk"
date: "2022-10-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Documentation of cleaning

This is a documenation of the cleaning round in October 2022. Mainly serves to create a searchable commit. But also to keep track of changes.

## next step

-   TODO HERE going on producing output for each model in order to summarise it into a common document and use for average barplots
-   TODO HERE go on with plotting things : currently : `plot_modelwise_GDM` and `plot_unique_GDM` . Need to create input for average over threshold plots, and either move to separate script or include in plot_modelwise_GDM.
    -   Add description in the powerpoint readme about plot_modelwise_GDM which iterates over model_names, and plot_unique which is only runned once.
-   TODO HERE GDM_multifun_thresholds : just started
-   merge scripts alpha_plots.Rmd and introductory_plots.Rmd

## Major topics of scripts

-   data assembly (create input data) ok
-   analysis (create output data)
-   visualisation and summarising (create summaries and plots from output data)

## Documentation of cleaning

-   Added documentation of datasets
-   `plot_GDM.Rmd` :
    -   removed `automaticrun` variable : all runs are automatic from now.

    -   chosing model from `model_names`.

    -   3 functions for the same job, just different dataset : `create_bio_aboveground_barplot`, `create_bio_belowground_barplot`, `create_abio_barplot`. Lession learned for future project : do a common function for the same types of plots

    -   reading in LUI input : before I gave the variable `compon_lui` by hand, now this is called `lui` and taken from `model_names_selecton$lui`.

    -   renamed to plot_modelwise_GDM. Only contains plots which are produced for each model indivdually. All other plots (that only need to be runned once = unique run) are in plot_unique_GDM

**small datasets**

small datasets that are stored in /vignettes are transferred to /data

`usethis::use_data(\<nameofdataset\>)` if necessary with `overwrite = T` to overwrite existing dataset

No loading is needed, because R packages use "lazy-loading", i.e. only load data when necessary.

**model_names**

will be used uniquely to select the current model to run, or to run all of them.

names need to be cleaned!

-   model_names column "name" renamed to "modelname"

-   added columns : funs, lui containing more info about the selected model --\> reduce the amount of hand-filled input

-   `model_names` column `luiinput` will not be used in the future any more : there will not be a model with all 3 components together, but only with individual ones. (because LUI components are correlated.)

### thresholds

-   Dec 22 Implemented new calculation of average over all threshold : NEW is that the avearage is not only calcluated for the maximum values, but across all 200 values of each predictor. Therefore, the function `plotUncertainty_sd` has been depreciated, and a new function `plotUncertainty_slim` was implemented.

    -   all models have to be re-runned on the cluster. (including updater of the cluster scripts documentation.

## Problematic scripts

-   GDM_multifun_thresholds

**prepare_and_run_GDM.Rmd**

implement the use of the `model_names` table. Select used models with `model_names_selection`.

-   `funs` needs to be changed to `model_names_selection$funs`

-   compon_luli is depreciated: use `lui` instead

-   replaced `modelname` with `model_names_selection$modelname`

## Sequence of analysis steps

-   is in file `the_analysis_hive.Rmd` now. (hive-drone wording is used here)

## Files

-   [ ] alpha_plots.Rmd
-   [x] 0 analysis_nonpublic.R betadiversity_imputation.R betadiversity_imputation.Rmd
-   [x] 2 calc_betadiversities.Rmd (calc_betadiversities.html)
-   [x] 1b calc_covariates.Rmd
-   [x] calc_LUI.Rmd
-   [x] 4b calc_multifun_from_imputed_additional_sensitivity.R
-   [x] 4 calc_multifun_from_imputed.Rmd
-   [ ] check_GDM_input_GAM.Rmd
-   [ ] check_GDM_input.Rmd
-   [x] 1a clean_and_load_soil_covariates.Rmd
-   [ ] cluster_scripts_documentation.Rmd
-   [ ] detect_GDM_effect_shape.Rmd
-   [ ] explore_functions_dataset.Rmd
-   [ ] filenames.txt
-   [x] 3 function_imputation.Rmd
-   [ ] gdm_model_diagnostics_overview.pdf
-   [ ] GDM_multifun_thresholds.Rmd
-   [ ] GDM_predictions.Rmd
-   [ ] GDM_pvalues_test.R
-   [ ] GDM_sensitivity_indirect_beta_effects.Rmd
-   [ ] introductory_plots.Rmd
-   [ ] package_testing.Rmd
-   [ ] plot_GDM.Rmd
-   [x] prepare_and_run_GDM.Rmd
-   [ ] quick_singlefunctions_plot.R
-   [ ] README_how-to-use-this-package.html (README_how-to-use-this-package.Rmd)
-   [ ] result_GDM_model_diagnostics_plots.Rmd
-   [ ] sensitivity_GDM_variable_sequence_does_not_matter.R
-   [ ] sensitivity_small_extras.Rmd
-   [ ] single_functions_effect_on_multifunctionality.Rmd
-   [ ] suppl_analysis_differences_in_richness.Rmd
-   [ ] THEORY_simulate_betadiversity.R

**helper_datasets**

from vignettes/

-   [x] nicenames.csv (added to /data)
-   [x] nicenames_old_may2021.csv (added to /old)
-   [x] helper_model_names.csv (added to /data)

from data_assembly/helper_data and analysis/helper_data

-   `usefulplotids` added to /data

-   `colorder_gdm_input` added to /data

## clean

Evaluate if useful content is in there, think about what to do later.

-   [ ] GDM_multifun_betadiv_lui_analysis.Rmd

# Re-Analysis

Take care that the following points are included in re-analysis :

-   %var expl. plot is re-done. Seems there was an error in manually entering the values in a large table. New : use the small tables extracted for each model and rbind them to a full table of model specs.

-   Implement permutations in `plot_GDM.Rmd`.

## Future todos

-   document data

-   screen through all scripts and solve remaining #TODO

-   remove `sections_to-be_loaded` in the end of every script!
