---
title: "alpha_diversity_plots"
author: "Noelle Schenk"
date: "11/20/2019"
output: html_document
---
requirements : `masterdiversity` in the file "master_diversity_alpha_beta.rds", see file analysis_nonpublic.R
- `trlevels`
- `master_alpha`
```{r}
masterdiversity <- data.table(masterdiversity)
require(cowplot)
require(RColorBrewer)
library(viridis)
```

# all trophic levels

number of species in plots
```{r}
master_alpha <- data.table::data.table(master_alpha)
master_alpha <- master_alpha[Var1 %in% plotNAset, ]
# transform bacteria to 1/1000 [k#]
gmaster_alpha <- master_alpha[, bacteria.RNA.alpha.k := bacteria.RNA.alpha / 1000]
gmaster_alpha[, bacteria.RNA.alpha := NULL]

gmaster_alpha <- melt(gmaster_alpha, id.vars = "Var1")
gtrlevel_names <- unique(gmaster_alpha$variable)

# ggplot(gmaster_alpha, aes(x = variable, y = value)) +
  # geom_point()
i <- gtrlevel_names[2]
ggplot(gmaster_alpha[variable == i], aes(x = variable, y = value)) +
  geom_point() +
  xlab("") + ylab("alpha diversity")
```


alpha-alpha plots, coloured by betadiversity.
```{r, eval = F}
jitter <- position_jitter(width = 0.1, height = 0.1)

for(t in trlevels){
  t_colnames <- grep(t, colnames(masterdiversity), value = T)
  subset <- masterdiversity[, ..t_colnames]
  
  namesref <- c(
    "alpha" = paste(t, ".alpha", sep = ""),
    "alpha2" = paste(t, ".alpha.2", sep = ""),
    "beta.sim" = paste(t, ".beta.sim", sep = ""),
    "beta.sne" = paste(t, ".beta.sne", sep = "")
  )
  
  plot_turnover <- ggplot(subset, aes(y = get(namesref[["alpha"]]), x = get(namesref[["alpha2"]]))) +
    geom_point(aes(colour = get(namesref[["beta.sim"]])), size = 4, position = jitter) +
    scale_colour_viridis_c() +
    ggtitle(label = t, subtitle = "coloured by turnover") + 
    xlab("alpha diversity plot 1") + ylab("alpha diversity plot 2") +
    labs(colour = "beta")
  
  plot_nestedness <- ggplot(subset, aes(y = get(namesref[["alpha"]]), x = get(namesref[["alpha2"]]))) +
    geom_point(aes(colour = get(namesref[["beta.sne"]])), size = 4, position = jitter) +
    scale_colour_viridis_c() +
    ggtitle(label = t, subtitle = "coloured by nestedness") + 
    xlab("alpha diversity plot 1") + ylab("alpha diversity plot 2") +
    labs(colour = "beta")
  
  plotname <- paste("plot_alpha_", t, sep = "")
  p <- plot_grid(plot_turnover, plot_nestedness,rel_widths = 1, rel_heights = 1, labels = c("to", "nes"), align = "h")
  assign(plotname, p)
  
  ggsave(filename=paste(plotname, "_coloured_by_beta.pdf", sep = ""), plot = p, device=cairo_pdf,
       width = 11.96, height = 8.27, units = "in", dpi = 900)
  
}
rm(p); rm(plot_nestedness); rm(plot_turnover); rm(subset); rm(namesref); rm(t); rm(t_colnames); rm(plotname)
```


# calc pairwise richness dist

```{r}
richness_diff_beta <- data.table::copy(data.table(masterdiversity))
is.data.table(richness_diff_beta)

for(t in trlevels){
  t_colnames <- grep(t, colnames(richness_diff_beta), value = T)
  namesref <- c(
    "alpha" = paste(t, ".alpha", sep = ""),
    "alpha2" = paste(t, ".alpha.2", sep = ""),
    "beta.sim" = paste(t, ".beta.sim", sep = ""),
    "beta.sne" = paste(t, ".beta.sne", sep = ""),
    "alpha.diff" = paste(t, ".alpha.diff", sep = "")
  )
  richness_diff_beta[, namesref["alpha.diff"] := abs(get(namesref[["alpha"]]) - get(namesref[["alpha2"]]))]
  # deleteme <- c(namesref[["alpha"]], namesref[["alpha2"]])
  # richness_diff_beta[, (deleteme) := NULL]
}
```
```{r}
plot(richness_diff_beta$autotroph.beta.sne, richness_diff_beta$autotroph.alpha.diff)
plot(richness_diff_beta$autotroph.beta.sim, richness_diff_beta$autotroph.alpha.diff)
plot(richness_diff_beta$autotroph.beta.sim + richness_diff_beta$autotroph.beta.sne, richness_diff_beta$autotroph.alpha.diff)

plot(richness_diff_beta$secondary.consumer.beta.sne, richness_diff_beta$secondary.consumer.alpha.diff)
plot(richness_diff_beta$secondary.consumer.beta.sne + richness_diff_beta$secondary.consumer.beta.sim, richness_diff_beta$secondary.consumer.alpha.diff)
plot(richness_diff_beta$secondary.consumer.alpha.2, richness_diff_beta$secondary.consumer.alpha.diff)

```

The difference is species which are in common.

Quick and dirty
```{r}
#TODO : ins Reine schreiben 

plot(richness_diff_beta$autotroph.beta.sne, richness_diff_beta$autotroph.alpha.diff / richness_diff_beta$autotroph.gamma, main = "nestedness weighted by gamma") # because alpha.diff includes both nestedness and turnover. Take gamma away from alpha diff --> more correlation?
plot(richness_diff_beta$autotroph.beta.sne + richness_diff_beta$autotroph.beta.sim, richness_diff_beta$autotroph.alpha.diff / richness_diff_beta$autotroph.gamma, main = "alpha weighted by gamma, full betadiversity") 
plot(gamma$autotroph.beta.sne/ gamma$autotroph.gamma, gamma$autotroph.alpha.diff)
plot(gamma$autotroph.beta.sne, gamma$autotroph.gamma)

# beta = gamma + alpha oder so
#TODO nachschauen!
```

