---
title: "Model diagnostics"
author: "N. V. Schenk"
date: '2022-07-29'
output:
  pdf_document: default
  html_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = F}
sections_to_be_loaded <- c()
source("vignettes/analysis_nonpublic.R")
```
# Header
Aim : create diagnostic plots of the models and compare.

The respective input datasets are loaded just before plotting.


# Model diagnostic plots
Some of the diagnostic plots of the GDMs look very crappy. Does the %deviance explained correspond to the crappyness of the GDM model fit?

## EFdist
High % dev expl
```{r}
efdist <- readRDS(paste(pathtodata, "/analysis/output_datasets/gdm_EFdistance_LUI_output.Rds", sep = ""))
# efdist$explained # 29.99
cairo_pdf(paste("vignettes/out/gdm_EFdistance_LUI_GDM_diagnostic_plot.pdf", sep = ""), width = 11.7, height = 8.3)
plot_diagn_gdm(efdist, title = "Efdistane")
dev.off()
```


## EF turnover
```{r, eval = F, include = T}
efto0.5 <- readRDS(paste(pathtodata, "/analysis/output_datasets/gdm_EFturnover_0.5_LUI_output.Rds", sep = ""))
efto0.5$explained # 12.19
plot_diagn_gdm(efto0.5)
```
```{r}
# 9 plots
EFturnover_varexpl <- list()
for(i in seq(0.1, 0.9, 0.1)){
  print(i)
  mod <- readRDS(paste(pathtodata, "/analysis/output_datasets/gdm_EFturnover_", i, "_LUI_output.Rds", sep = ""))
  EFturnover_varexpl <- append(EFturnover_varexpl, mod$explained)
  cairo_pdf(paste("vignettes/out/gdm_EFturnover_",i ,"_LUI_diagnostic_plot.pdf", sep = ""), width = 11.7, height = 8.3)
  plot_diagn_gdm(mod, title = paste("EFturnover", i))
  dev.off()
}
# EFturnover_varexpl
```


# EF nestedness
```{r}
# 9 plots
EFnestedness_varexpl <- list()
for(i in seq(0.1, 0.9, 0.1)){
  print(i)
  mod <- readRDS(paste(pathtodata, "/analysis/output_datasets/gdm_EFnestedness_", i, "_LUI_output.Rds", sep = ""))
  EFnestedness_varexpl <- append(EFnestedness_varexpl, mod$explained)
  plot_diagn_gdm(mod, title = paste("EFnestedness", i))
}
# EFnestedness_varexpl
```


```{r}
#TODO add diagnostics for single Functions models
```

