---
title: "plot GDM"
author: "Noelle Schenk"
date: "August 20, 2019"
output: html_document
---
requirements : 
- GDM output as .rds, e.g. gdm_EFnestedness_LUI_input.Rds
- cluster output as .rds, e.g. gdm_EFnestedness_LUI_permutation.Rds
```{r}
suppressPackageStartupMessages(library(cowplot)) # needs to be loaded in order to use it (even within R package)
```


Load data
```{r}
# gdmin <- readRDS(paste(pathtoout, "/cluster/gdm_EFdistance_LUI_input.Rds", sep = ""))
# gdmin <- readRDS(paste(pathtoout, "/cluster/gdm_EFnestedness_LUI_input.Rds", sep = ""))
# gdmin <- readRDS(paste(pathtoout, "/cluster/gdm_EFturnover_LUI_input.Rds", sep = ""))
gdmin <- readRDS(paste(pathtoout, "/cluster/gdm_EFbeta_LUI_input.Rds", sep = ""))

gdm_output <- gdm::gdm(gdmin, geo = F, splines = NULL, knots = NULL)
exSplines <- gdm::isplineExtract(gdm_output)

gdmperm <- readRDS(paste(pathtoout, "/cluster/gdm_EFdistance_LUI_permutation.Rds", sep = ""))
# gdmperm <- readRDS(paste(pathtoout, "/cluster/gdm_EFnestedness_LUI_permutation.Rds", sep = ""))

permut <- F # T or F, depending wether permutations are available or not
main <- "EFbeta LUI" # plot title
```
```{r}
# take maximum of each variable for barplot
maxsplines <- apply(exSplines$y, 2, max, na.rm = TRUE)
# get significances
if(permut == T){sign <- gdmperm[[3]][,1]}
```
create plotting tables

Sequence according to effect sizes over all models. until then : alphabetically.
```{r}
#TODO : once all models are read, use effect size sequence and not alphabetically
plotsequence_bio <- c("autotroph", "bacteria.RNA", "belowground.herbivore", "belowground.predator", "herbivore", "plant.pathogen", "pollinator", "protist.bacterivore", "protist.eukaryvore", "protist.omnivore", "protist.plant.parasite", "secondary.consumer", "soilfungi.decomposer", "soilfungi.pathotroph", "soilfungi.symbiont", "tertiary.consumer")
#TODO : add characteristic color for each trophic level
plotsequence_abio <- c("LUI", "deltaLUI", "soil", "isolation", "geo")
```

create results table
```{r}
restab <- data.table::data.table("names" = names(maxsplines), "maxsplines" = maxsplines)
if(permut == T){
  del <- data.table::data.table("names" = names(sign), "sign" = sign)
  restab <- data.table::data.table(merge(restab, del, by = "names")); rm(del)
}
# get bios
bios <- grep(paste(plotsequence_bio, collapse = "|"), names(maxsplines), value = T)
restab[names %in% bios, type := "bio"]
# get abios
abios <- grep(paste(plotsequence_bio, collapse = "|"), names(maxsplines), value = T, invert = T)
restab[names %in% abios, type := "abio"]
# get nestedness
sne <- grep("sne", names(maxsplines), value = T)
restab[names %in% sne, component := "nestedness"]
# get turnover
to <- grep("sim", names(maxsplines), value = T)
restab[names %in% to, component := "turnover"]
# get only significant
if(permut == T){restab[, maxsplines := (1-sign) * maxsplines]}
# add nice names
restab <- data.table::data.table(merge(nicenames, restab, by = "names"))
# order by above-belowground and alphabetically
# set the levels of the factor in the wanted order
data.table::setorder(restab, ground, names)
# restab[, names := factor(names, levels = names)]
# order <- restab[type == "bio", names]
# bring colors into right format
restab[, color := as.character(color)]
```
colors for plotting (21), 16 in the bio plot
```{r, eval = F}
# from pallettes Dark2, Set1 and Accent from RColorBrewer
cbcols <- c("#1B9E77","#D95F02", "#7570B3", "#E7298A", "#66A61E", "#E6AB02", "#A6761D", "#666666",
             "#377EB8", "#984EA3", "#A65628", "#F781BF",
            "#7FC97F", "#BEAED4","#FDC086", "#FFFF99")
restab[component == "turnover", color := cbcols ]
restab[component == "nestedness", color := cbcols]
restab[type == "abio", color := cbcols[1:length(restab[type == "abio", color])]]
# varcols <- restab$color
# names(varcols) <- restab$names
```


simple plot
```{r, eval = F}
# to plot each spline in a separate plot
plot(gdm_output, plot.layout = c(3, 2), plot.color = "grey", main="GDM")
```


# Multipanel Barplot

```{r}
df <- restab[type == "bio" & ground == "a", ]
p<-ggplot(data = df, aes(x=nicenames, y=maxsplines, fill = names)) +
  geom_bar(stat="identity", color = "black", linetype = rep(c("solid", "dashed"), nrow(df)/2)) + 
  coord_flip() + 
  scale_fill_manual(values = df$color) +
  ylim(0, 0.4) + 
  ggtitle(main) +
  theme(legend.position = "none", axis.title = element_blank(),
        axis.text.y = element_text(size=9, angle = 0),
        plot.margin = margin(l = 50), 
        axis.text.x = element_blank(),
        axis.line.x=element_blank(),
        axis.ticks.x = element_blank(),
        panel.grid.major.x = element_line(color = "grey")
        )

df <- restab[type == "bio" & ground == "b", ]
b <- ggplot(data = df, aes(x=nicenames, y=maxsplines, fill = names)) +
  geom_bar(stat="identity", color = "black", linetype = rep(c("solid", "dashed"), nrow(df)/2)) + 
  coord_flip() + 
  scale_fill_manual(values = df$color) +
  ylim(0, 0.4) + 
  theme(legend.position = "none", 
        axis.title = element_blank(),
        axis.text.y = element_text(size=9, angle = 0),
        plot.margin = margin(l = 50),
        axis.text.x = element_blank(),
        axis.line.x=element_blank(),
        axis.ticks.x = element_blank(),
        panel.grid.major.x = element_line(color = "grey"))
# aes(x=stringr::str_wrap(nicenames, 10), y=onlysign, fill = names))

# dashed or dotted or solid
# https://stackoverflow.com/questions/39898870/ggplot-geom-bar-customize-by-linetype-and-fill
# geom_errorbarh() for horizontal error bars
# https://www.heropatterns.com/
df <- restab[type == "abio"]
q <- ggplot(data = df, aes(x=nicenames, y=maxsplines, fill = names)) +
  geom_bar(stat="identity", color = "black", linetype = "solid") + 
  coord_flip() + 
  scale_fill_manual(values = df$color) +
  ylim(0, 0.4) + 
  theme(legend.position = "none", axis.title = element_blank(),
        axis.text.y = element_text(size=9),
        panel.grid.major.x = element_line(color = "grey"))
```

```{r, eval = F}
plot_grid(p, b, q, labels = c('A', '', 'B'), label_size = 12, nrow = 3, rel_heights = c(0.31, 0.51, 0.18), align = "v")
# plot_grid(p, b, q, labels = c('aboveground', 'belowground', 'abiotic'), label_size = 12, nrow = 3, rel_heights = c(0.31, 0.51, 0.18), align = "v")
```








