---
title: "summarise_GDM_results"
author: "N. Schenk"
date: "2022-11-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Aim
Summarise the results of all GDM models listed in the table `model_names` and create a results table `GDM_results`.
Serves as input for assessing the thresholds and comparing quality of the models, nad the summary models across thresholds.

# Requirements
- run all the previous scripts to generate necessary output

```{r}
source("vignettes/analysis_nonpublic.R")

for(m in model_names[model_class %in% "multifun" & lui == "LUI", modelname]){
  #TODO waiting until results for all theses models have been generated by the_analysis_hive.Rmd
}


gdmoutput <- readRDS(paste_gdm_input_path_together(pathtoout = pathtodata, name = model_name))
  model_specs <- data.table::fread(paste(pathtodata, "/analysis/output_datasets/", 
                          model_names_selection$modelname, "_GDM_model_specs.csv", sep = ""))
sections_to_be_loaded <- c("gdmoutput")
```


